# Generated by Django 4.1.7 on 2023-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_recipe_options_recipe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
